ktor:
  application:
    modules:
      - ir.irancell.application.ApplicationKt.module
  deployment:
    port: 80
    host: "0.0.0.0"
postgres:
  url: "jdbc:postgresql://localhost/abcem_database"
  user: "postgres"
  password: "afshin1994"
  driver: "org.postgresql.Driver"