ktor:
  application:
    modules:
      - ir.irancell.application.ApplicationKt.module
  deployment:
    port: 80


postgres:
  command:
      url: "jdbc:postgresql://localhost/abcem_database"
      user: "postgres"
      password: "afshin1994"
      driver: "org.postgresql.Driver"

  query:
      url: "jdbc:postgresql://localhost/abcem_database"
      user: "postgres"
      password: "afshin1994"
      driver: "org.postgresql.Driver"